import { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { Category, categoryMeta, useExpenses } from "@/lib/expense-store";

const categories: ("All" | Category)[] = ["All", "Food", "Transport", "School", "Shopping", "Bills", "Fun", "Health", "Other"];
const money = (value: number) => `₱${value.toLocaleString("en-PH", { maximumFractionDigits: 0 })}`;
const dateLabel = (value: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(`${value}T12:00:00`));

export default function TransactionsScreen() {
  const { sortedExpenses, removeExpense } = useExpenses();
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<"All" | Category>("All");
  const filtered = useMemo(() => sortedExpenses.filter((expense) => `${expense.description} ${expense.category} ${expense.payment}`.toLowerCase().includes(query.toLowerCase()) && (category === "All" || expense.category === category)), [sortedExpenses, query, category]);
  const total = filtered.reduce((sum, expense) => sum + expense.amount, 0);

  return <ScreenContainer><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><Text style={styles.kicker}>YOUR MONEY TRAIL</Text><Text style={styles.title}>Transactions<Text style={styles.dot}>.</Text></Text><Text style={styles.subtitle}>Every peso has a place. Keep the record clear.</Text><View style={styles.summary}><View><Text style={styles.summaryLabel}>SHOWING</Text><Text style={styles.summaryValue}>{filtered.length} records</Text></View><View style={styles.divider} /><View><Text style={styles.summaryLabel}>FILTERED TOTAL</Text><Text style={styles.summaryValue}>{money(total)}</Text></View></View><View style={styles.search}><Ionicons name="search" size={17} color="#A3ADA8" /><TextInput value={query} onChangeText={setQuery} placeholder="Search transactions" placeholderTextColor="#A3ADA8" style={styles.searchInput} /></View><View style={styles.filterHeader}><Ionicons name="funnel-outline" size={15} color="#899590" /><Text style={styles.filterLabel}>FILTER BY CATEGORY</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{categories.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.chip, category === item && styles.chipActive]}><Text style={[styles.chipText, category === item && styles.chipTextActive]}>{item}</Text></Pressable>)}</ScrollView><View style={styles.list}>{filtered.map((expense) => <View style={styles.row} key={expense.id}><View style={[styles.icon, { backgroundColor: categoryMeta[expense.category].soft }]}><Ionicons name="card-outline" size={16} color={categoryMeta[expense.category].color} /></View><View style={styles.body}><Text style={styles.name}>{expense.description}</Text><Text style={styles.meta}>{expense.category}  ·  {expense.payment}</Text><Text style={styles.date}>{dateLabel(expense.date)}</Text></View><View style={styles.amountColumn}><Text style={styles.amount}>−{money(expense.amount)}</Text><Pressable onPress={() => Alert.alert("Delete expense?", `Remove ${expense.description} from your records?`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => removeExpense(expense.id) }])}><Ionicons name="trash-outline" size={15} color="#A3ADA8" /></Pressable></View></View>)}</View>{filtered.length === 0 && <View style={styles.empty}><Ionicons name="search" size={21} color="#A3ADA8" /><Text style={styles.emptyTitle}>No transactions found</Text><Text style={styles.emptyText}>Try another search or filter.</Text></View>}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ scroll: { paddingTop: 13, paddingBottom: 28 }, kicker: { color: "#EB6F61", fontSize: 10, fontWeight: "800", letterSpacing: 1.4 }, title: { fontFamily: "Fraunces_700Bold", color: "#26312E", fontSize: 35, fontWeight: "700", letterSpacing: -1.4, marginTop: 8 }, dot: { color: "#EB6F61" }, subtitle: { fontFamily: "Fraunces_700Bold", color: "#899590", fontSize: 12, marginTop: 6 }, summary: { flexDirection: "row", alignItems: "center", gap: 18, marginTop: 25, marginBottom: 20 }, summaryLabel: { color: "#A3ADA8", fontSize: 9, fontWeight: "800", letterSpacing: 1 }, summaryValue: { color: "#26312E", fontSize: 18, fontWeight: "700", marginTop: 5 }, divider: { width: 1, height: 32, backgroundColor: "#E5EBE7" }, search: { flexDirection: "row", alignItems: "center", gap: 8, height: 43, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: "#E5EBE7", backgroundColor: "#FFFFFF" }, searchInput: { flex: 1, color: "#26312E", fontSize: 11 }, filterHeader: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 21, marginBottom: 9 }, filterLabel: { color: "#899590", fontSize: 9, fontWeight: "800", letterSpacing: 1 }, chips: { gap: 7, paddingBottom: 3 }, chip: { height: 32, paddingHorizontal: 11, alignItems: "center", justifyContent: "center", borderRadius: 8, borderWidth: 1, borderColor: "#E5EBE7", backgroundColor: "#FFFFFF" }, chipActive: { borderColor: "#F2B8B0", backgroundColor: "#FFF0ED" }, chipText: { color: "#899590", fontSize: 10 }, chipTextActive: { color: "#EB6F61", fontWeight: "700" }, list: { marginTop: 16, paddingHorizontal: 15, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5EBE7" }, row: { flexDirection: "row", alignItems: "center", gap: 10, minHeight: 72, borderBottomWidth: 1, borderBottomColor: "#EEF2EF" }, icon: { width: 34, height: 34, alignItems: "center", justifyContent: "center", borderRadius: 10 }, body: { flex: 1 }, name: { color: "#26312E", fontSize: 11, fontWeight: "700" }, meta: { color: "#A3ADA8", fontSize: 9, marginTop: 4 }, date: { color: "#A3ADA8", fontSize: 9, marginTop: 5 }, amountColumn: { alignItems: "flex-end", justifyContent: "space-between", gap: 9 }, amount: { color: "#26312E", fontSize: 12, fontWeight: "700" }, empty: { alignItems: "center", gap: 7, paddingVertical: 60 }, emptyTitle: { color: "#26312E", fontSize: 18, fontWeight: "700" }, emptyText: { color: "#A3ADA8", fontSize: 11 } });
